# GitHub learn Actions
# Test comment - Basics actions
name: codewars-examples
env:
  APPLICATION_NAME: "CODEWARS"
  PACKAGE: "CODEWARS ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, world! from build"
      - name: Execute few commands
        run: |
          echo "Hello Message 1"
          echo "Hello Message 2"
          echo "Application name ${{ env.APPLICATION_NAME }}"
      - name: List current folder
        run: ls -la
      - name: Git clone codewars repository
        uses: actions/checkout@v1
      - name: List current folder
        run: ls -la

  test:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      VAR1: "THIS IS LOCAL VARIABLE FROM TEST JOB"

    steps:
      - name: Print Hello Message
        run: echo "Hello, world from test!"
      - name: Print Env Test Job Vars
        run: |
          echo "TEST JOB Var - ${{ env.VAR1 }}"
          echo "TEST LOCAL Var - $VAR2"
        env:
          VAR2: "THIS IS LOCAL VARIABLE FROM STEP"
      - name: Test Package
        run: echo "Test Package ${{ env.PACKAGE }}"